export default {
  singleQuote: false,
  semi: true,
  tabWidth: 2,
  printWidth: 100,
  proseWrap: "always",
  trailingComma: "all",
  endOfLine: "lf",
  importOrder: ["<THIRD_PARTY_MODULES>", "^@/(.*)$", "^[./]"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: true,
  importOrderParserPlugins: ["typescript", "typescript-jsx"],
  sortPackageJson: false,
  ignorePatterns: ["dist", "node_modules", "pnpm-lock.yaml", ".changeset/README.md"],
};
